version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: seletivoseplag
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: seletivoseplagmt
    ports:
      - "5433:5432"
#    volumes: # apagar se for usar o portainer
#      - /projetos/docker/volumes/postgresql:/var/lib/postgresql/data # apagar se for usar o portainer
  minio:
    image: minio/minio
    container_name: minio_server
    restart: always
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    ports:
     - "9000:9000"
     - "9001:9001"
    command: server --console-address ":9001" /data
#    volumes:
#     - /projetos/docker/volumes/minio:/data



